vertex:
  prefix: '#ffc84aVAC§7'

punish-effect:
  enabled: true
  particle_count: 80
  duration_ticks: 3
  particle: "FLAME"
  sound: "ENTITY_DRAGON_FIREBALL_EXPLODE"

alerts:
  # {prefix}
  # {player}
  # {check}
  # {violations}
  message: "{prefix} #ffebba{player} #ffc84afailed #ffebba{check} #ffc84a#{violations}"
  enable-alerts-on-join: true

messages:
  no-permission: "§cYou don't have permission to use this command"
  alerts:
    alerts-enabled: "§aОповещения включены"
    alerts-disabled: "§cОповещения выключены"
  checks:
    header: "#ffc84aВключённые проверки:"
    check: "#ffc84a- #ffebba{check}"
  config:
    config-reload: "§aПерезагрузка конфига..."
    config-reloaded: "§aКонфиг перезагружен"
  commands: |
    #ffc84a- #ffebba/vertex reload &7- перезагрузка конфига
    #ffc84a- #ffebba/vertex checks &7- включённые проверки
    #ffc84a- #ffebba/vertex help &7- помощь
    #ffc84a- #ffebba/vertex alerts &7- включить/выключить оповещения

checks:
  AimA: # снапы
    max-violations: 5
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.05
    hit-cancel-ticks: 40

  AimB: # округление
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.1
    hit-cancel-ticks: 10

  AimC: # надеюсь кириешко не против
    max-violations: 15
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 3
    buffer-decrease: 0.25
    hit-cancel-ticks: 10

  AimD: # плавный аим
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    hit-cancel-ticks: 40

  AimE: # статик ротации
    max-violations: 15
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 7
    buffer-decrease: 0.5
    hit-cancel-ticks: 20

  AimF: # очень маленькие дельты
    max-violations: 30
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.05
    hit-cancel-ticks: 15

  AimG: # не настраивал
    max-violations: 30
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.25
    hit-cancel-ticks: 20

  AimH: # не настраивал
    max-violations: 30
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.25
    hit-cancel-ticks: 15

  AimI: # не настраивал
    max-violations: 30
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.25
    hit-cancel-ticks: 15

  AimJ:
    max-violations: 30
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    hit-cancel-ticks: 15

  AuraA: # ест и бьёт
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 2
    buffer-decrease: 0.5
    hit-cancel-ticks: 100

  AuraB: # удары через стену
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 3
    buffer-decrease: 0.5
    hit-cancel-ticks: 60
    hitbox-expand: 0.25

  AuraC: # автокликер чё
    max-violations: 15
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 1
    buffer-decrease: 1
    hit-cancel-ticks: 20

  AuraD: # снапы
    max-violations: 10
    remove-violations-after: 60 # seconds
    decay: 1
    enabled: true
    alert: true
    punish-command: 'kick {player} #ff7b42Unfair Advantage'
    max-buffer: 1
    buffer-decrease: 0.25
    hit-cancel-ticks: 20

  # data
  ActionData:
    combat-ticks: 60